/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.ParseException;
import javax.swing.text.MaskFormatter;

public class formCadastroVaga extends javax.swing.JFrame {

    Conexao con_cliente;
    MaskFormatter mfSalario;
    /**
     * Creates new form formCadastroVaga
     */

    public formCadastroVaga() {
        try {
        mfSalario = new MaskFormatter ("");
        initComponents();
        con_cliente = new Conexao();
        con_cliente.conecta();
        con_cliente.executaSQL("select * from vagas order by ID_Vaga");
        preencherTabela();
        posicionarRegistro();
        } catch (ParseException ex) {
            System.out.println("Erro na mascara");
        }

        
        vagas.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        label_ID_Vaga = new javax.swing.JLabel();
        label_N_Vagas = new javax.swing.JLabel();
        label_Cargo = new javax.swing.JLabel();
        label_Descricao = new javax.swing.JLabel();
        label_Salario = new javax.swing.JLabel();
        txtID_Vaga = new javax.swing.JTextField();
        txt_N_Vagas = new javax.swing.JTextField();
        txt_Cargo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        vagas = new javax.swing.JTable();
        btnGravar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Descricao = new javax.swing.JTextArea();
        txt_Salario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        labelTitulo.setText("Cadastro de Vagas");

        label_ID_Vaga.setText("Codigo Vaga");

        label_N_Vagas.setText("Numero de vagas");

        label_Cargo.setText("Cargo");

        label_Descricao.setText("Descriçao");

        label_Salario.setText("Salario");

        vagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Vaga", "N_Vagas", "Cargo", "Salario", "Descricao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vagasMouseClicked(evt);
            }
        });
        vagas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vagasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(vagas);

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Save.png"))); // NOI18N
        btnGravar.setText("Salvar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Notes.png"))); // NOI18N
        btnAlterar.setText("Atualizar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Erase.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Exit.gif"))); // NOI18N
        btnVoltar.setText("Voltar ao Menu");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/New document.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        txt_Descricao.setColumns(20);
        txt_Descricao.setRows(5);
        jScrollPane1.setViewportView(txt_Descricao);

        txt_Salario.setText("Ex: 1.000,50");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGap(106, 106, 106)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_ID_Vaga)
                                    .addComponent(label_Descricao)
                                    .addComponent(label_Salario)
                                    .addComponent(label_Cargo))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtID_Vaga, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(50, 50, 50)
                                            .addComponent(label_N_Vagas)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_N_Vagas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                    .addComponent(txt_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 19, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNovo)
                                        .addGap(45, 45, 45)
                                        .addComponent(btnGravar)
                                        .addGap(134, 134, 134)
                                        .addComponent(btnAlterar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnExcluir)))))
                        .addGap(14, 14, 14)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(btnVoltar))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ID_Vaga)
                    .addComponent(txtID_Vaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_N_Vagas)
                    .addComponent(txt_N_Vagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_Salario)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_Cargo)
                            .addComponent(txt_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Descricao)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo)
                            .addComponent(btnGravar)
                            .addComponent(btnAlterar)
                            .addComponent(btnExcluir))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vagasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vagasKeyPressed
        // TODO add your handling code here:
        int linha_selecionada = vagas.getSelectedRow();
        txtID_Vaga.setText(vagas.getValueAt(linha_selecionada, 0).toString());
        txt_N_Vagas.setText(vagas.getValueAt(linha_selecionada, 1).toString());
        txt_Cargo.setText(vagas.getValueAt(linha_selecionada, 2).toString());
        txt_Salario.setText(vagas.getValueAt(linha_selecionada, 3).toString());
        txt_Descricao.setText(vagas.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_vagasKeyPressed

    private void vagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vagasMouseClicked
        // TODO add your handling code here:
        int linha_selecionada = vagas.getSelectedRow();
        txtID_Vaga.setText(vagas.getValueAt(linha_selecionada, 0).toString());
        txt_N_Vagas.setText(vagas.getValueAt(linha_selecionada, 1).toString());
        txt_Cargo.setText(vagas.getValueAt(linha_selecionada, 2).toString());
        txt_Salario.setText(vagas.getValueAt(linha_selecionada, 3).toString());
        txt_Descricao.setText(vagas.getValueAt(linha_selecionada, 4).toString());

    }//GEN-LAST:event_vagasMouseClicked

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        String ID_vaga = txtID_Vaga.getText();
        String N_Vagas = txt_N_Vagas.getText();
        String Cargo = txt_Cargo.getText();
        String Salario = txt_Salario.getText();
        String Descricao = txt_Descricao.getText();

        try {
            String insert_sql = "insert into vagas (ID_Vaga,N_Vagas, Cargo, Salario, Descricao) values ('" + ID_vaga + "','" + N_Vagas + "','" + Cargo + "','" + Salario + "','" + Descricao + "')";
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação realizada com suesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from vagas order by ID_Vaga");
            con_cliente.resultset.first();

            mostrar_Dados();
            preencherTabela();
        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(null, "\n Erro na gravação :\n " + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        String ID_vaga = txtID_Vaga.getText();
        String N_Vagas = txt_N_Vagas.getText();
        String Cargo = txt_Cargo.getText();
        String Salario = txt_Salario.getText();
        String Descricao = txt_Descricao.getText();
        String sql = "";
        String msg = "";
        try {

            if (txtID_Vaga.getText().equals("")) {

                sql = "insert into vagas (ID_Vaga,N_Vagas, Cargo, Salario, Descricao) values ('" + ID_vaga + "','" + N_Vagas + "','" + Cargo + "','" + Salario + "','" + Descricao + "')";
                msg = "Gravação de um novo registro";
            } else {
                sql = "update vagas set ID_Vaga='" + ID_vaga + "',N_Vagas='" + N_Vagas + "', Cargo='" + Cargo + "', Salario='" + Salario + "', Descricao='" + Descricao + "' where ID_Vaga = " + txtID_Vaga.getText();
                msg = "Alteração de registro ";
            }
            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, msg + "Realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from vagas order by ID_Vaga");
            con_cliente.resultset.first();

            mostrar_Dados();
            preencherTabela();
        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(null, "\n Erro na gravação :\n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        String sql = "";
        try {
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro?  ", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, 3);
            if (resposta == 0) {
                sql = "delete from vagas where ID_Vaga = " + txtID_Vaga.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);
                if (excluir == 1) {
                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("Select * from vagas order by ID_Vaga");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistro();
                } else {
                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuario!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

                }
            }
        } catch (SQLException excecao) {
            JOptionPane.showMessageDialog(null, "Erro na exclusão!" + excecao, "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        txtID_Vaga.setText("");
        txt_N_Vagas.setText("");
        txt_Cargo.setText("");
        txt_Salario.setText("");
        txt_Descricao.setText("");
        txtID_Vaga.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void preencherTabela() {
        vagas.getColumnModel().getColumn(0).setPreferredWidth(3);
        vagas.getColumnModel().getColumn(1).setPreferredWidth(3);
        vagas.getColumnModel().getColumn(2).setPreferredWidth(80);
        vagas.getColumnModel().getColumn(3).setPreferredWidth(15);
        vagas.getColumnModel().getColumn(4).setPreferredWidth(150);

        // Obtenha o modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) vagas.getModel();

        // Limpe todas as linhas existentes na tabela
        modelo.setRowCount(0);

        try {
            // Posicione o cursor antes do primeiro registro
            con_cliente.resultset.beforeFirst();

            // Itere sobre os resultados e adicione cada linha à tabela
            while (con_cliente.resultset.next()) {
                modelo.addRow(new Object[]{
                    con_cliente.resultset.getString("ID_Vaga"),
                    con_cliente.resultset.getString("N_Vagas"),
                    con_cliente.resultset.getString("Cargo"),
                    con_cliente.resultset.getString("Salario"),
                    con_cliente.resultset.getString("Descricao")
                });
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar os dados da tabela: " + erro.getMessage(), "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void posicionarRegistro() {
        try {
            // Posicione o cursor no primeiro registro
            con_cliente.resultset.first();

            // Mostre os dados do registro atual
            mostrar_Dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no primeiro registro: " + erro.getMessage(), "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void mostrar_Dados() {
        try {
            // Exiba os dados do registro atual nos campos de texto
            txtID_Vaga.setText(con_cliente.resultset.getString("ID_Vaga"));
            txt_N_Vagas.setText(con_cliente.resultset.getString("N_Vagas"));
            txt_Cargo.setText(con_cliente.resultset.getString("Cargo"));
            txt_Salario.setText(con_cliente.resultset.getString("Salario"));
            txt_Descricao.setText(con_cliente.resultset.getString("Descricao"));
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não foi possível localizar dados: " + erro.getMessage(), "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCadastroVaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCadastroVaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCadastroVaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCadastroVaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCadastroVaga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel label_Cargo;
    private javax.swing.JLabel label_Descricao;
    private javax.swing.JLabel label_ID_Vaga;
    private javax.swing.JLabel label_N_Vagas;
    private javax.swing.JLabel label_Salario;
    private javax.swing.JTextField txtID_Vaga;
    private javax.swing.JTextField txt_Cargo;
    private javax.swing.JTextArea txt_Descricao;
    private javax.swing.JTextField txt_N_Vagas;
    private javax.swing.JTextField txt_Salario;
    private javax.swing.JTable vagas;
    // End of variables declaration//GEN-END:variables
}
