/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

/**
 *
 * @author Fatec
 */
import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.ParseException;
import javax.swing.text.MaskFormatter;

public class formCadastroEmpresa extends javax.swing.JFrame {

    Conexao con_cliente;
    MaskFormatter mfCNPJ;

    public formCadastroEmpresa() {
        try {
            mfCNPJ = new MaskFormatter ("##.###.###/####-##");
            initComponents();
            con_cliente = new Conexao();
            con_cliente.conecta();
            con_cliente.executaSQL("select * from empresa order by ID_Empresa");
            preencherTabela();
            posicionarRegistro();
            empresa.setAutoCreateRowSorter(true);
        } catch (ParseException ex) {
            System.out.println("Erro na mascara");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Estado = new javax.swing.JComboBox<>();
        txt_ID_Empresa = new javax.swing.JTextField();
        txt_Nome_Empresa = new javax.swing.JTextField();
        txt_Cidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        empresa = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();
        txt_CNPJ = new javax.swing.JFormattedTextField(mfCNPJ);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Empresa");

        label1.setText("Código da Empresa");

        jLabel3.setText("Nome da Empresa");

        jLabel4.setText("CNPJ");

        jLabel5.setText("Estado");

        jLabel6.setText("Cidade");

        txt_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        empresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código da Empresa", "Nome da Empresa", "CNPJ", "Estado", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empresaMouseClicked(evt);
            }
        });
        empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empresaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(empresa);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/New document.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Save.png"))); // NOI18N
        btnGravar.setText("Salvar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Notes.png"))); // NOI18N
        btnAlterar.setText("Atualizar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Erase.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Exit.gif"))); // NOI18N
        btnVoltar1.setText("Voltar ao Menu");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label1)
                                            .addComponent(jLabel3))
                                        .addComponent(jLabel5))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(btnGravar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAlterar)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnExcluir))
                                        .addComponent(txt_Nome_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_ID_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(160, 160, 160)
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(btnNovo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar1)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar1)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(txt_ID_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nome_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnGravar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        txt_ID_Empresa.setText("");
        txt_Nome_Empresa.setText("");
        txt_CNPJ.setText("");
        txt_Estado.setSelectedIndex(-1);
        txt_Cidade.setText("");
        txt_ID_Empresa.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        String ID_Empresa = txt_ID_Empresa.getText();
        String Nome_Empresa = txt_Nome_Empresa.getText();
        String CNPJ = txt_CNPJ.getText();
        String Estado = (String) txt_Estado.getSelectedItem();
        String Cidade = txt_Cidade.getText();

        try {
            String insert_sql = "insert into empresa (ID_Empresa,Nome_Empresa, CNPJ, Estado, Cidade) values ('" + ID_Empresa + "','" + Nome_Empresa + "','" + CNPJ + "','" + Estado + "','" + Cidade + "')";
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação realizada com suesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from empresa order by ID_Empresa");
            con_cliente.resultset.first();

            mostrar_Dados();
            preencherTabela();
        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(null, "\n Erro na gravação :\n " + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        String ID_Empresa = txt_ID_Empresa.getText();
        String Nome_Empresa = txt_Nome_Empresa.getText();
        String CNPJ = txt_CNPJ.getText();
        String Estado = (String) txt_Estado.getSelectedItem();
        String Cidade = txt_Cidade.getText();
        String sql = "";
        String msg = "";
        try {

            if (txt_ID_Empresa.getText().equals("")) {

                sql = "insert into empresa (ID_Empresa,Nome_Empresa, CNPJ, Estado, Cidade) values ('" + ID_Empresa + "','" + Nome_Empresa + "','" + CNPJ + "','" + Estado + "','" + Cidade + "')";
                msg = "Gravação de um novo registro";
            } else {
                sql = "update empresa set ID_Empresa='" + ID_Empresa + "',Nome_Empresa='" + Nome_Empresa + "', CNPJ='" + CNPJ + "', Estado='" + Estado + "', Cidade='" + Cidade + "' where ID_Empresa = " + txt_ID_Empresa.getText();
                msg = "Alteração de registro ";
            }
            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, msg + "Realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from empresa order by ID_Empresa");
            con_cliente.resultset.first();
            mostrar_Dados();
            preencherTabela();
        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(null, "\n Erro na gravação :\n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        String sql = "";
        try {
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro?  ", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, 3);
            if (resposta == 0) {
                sql = "delete from empresa where ID_Empresa = " + txt_ID_Empresa.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);
                if (excluir == 1) {
                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("Select * from empresa order by ID_Empresa");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistro();
                } else {
                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuario!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

                }
            }
        } catch (SQLException excecao) {
            JOptionPane.showMessageDialog(null, "Erro na exclusão!" + excecao, "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void empresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empresaMouseClicked
        // TODO add your handling code here:
        int linha_selecionada = empresa.getSelectedRow();
        txt_ID_Empresa.setText(empresa.getValueAt(linha_selecionada, 0).toString());
        txt_Nome_Empresa.setText(empresa.getValueAt(linha_selecionada, 1).toString());
        txt_CNPJ.setText(empresa.getValueAt(linha_selecionada, 2).toString());
        String estadoSelecionado = empresa.getValueAt(linha_selecionada, 3).toString();
        txt_Estado.setSelectedItem(estadoSelecionado);
        txt_Cidade.setText(empresa.getValueAt(linha_selecionada, 4).toString());
    }//GEN-LAST:event_empresaMouseClicked

    private void empresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empresaKeyPressed
        // TODO add your handling code here:
        int linha_selecionada = empresa.getSelectedRow();
        txt_ID_Empresa.setText(empresa.getValueAt(linha_selecionada, 0).toString());
        txt_Nome_Empresa.setText(empresa.getValueAt(linha_selecionada, 1).toString());
        txt_CNPJ.setText(empresa.getValueAt(linha_selecionada, 2).toString());
        String estadoSelecionado = empresa.getValueAt(linha_selecionada, 3).toString();
        txt_Estado.setSelectedItem(estadoSelecionado);
        txt_Cidade.setText(empresa.getValueAt(linha_selecionada, 4).toString());

    }//GEN-LAST:event_empresaKeyPressed

    private void preencherTabela() {
        empresa.getColumnModel().getColumn(0).setPreferredWidth(30);
        empresa.getColumnModel().getColumn(1).setPreferredWidth(100);
        empresa.getColumnModel().getColumn(2).setPreferredWidth(80);
        empresa.getColumnModel().getColumn(3).setPreferredWidth(8);
        empresa.getColumnModel().getColumn(4).setPreferredWidth(80);

        // Obtenha o modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) empresa.getModel();

        // Limpe todas as linhas existentes na tabela
        modelo.setRowCount(0);

        try {
            // Posicione o cursor antes do primeiro registro
            con_cliente.resultset.beforeFirst();

            // Itere sobre os resultados e adicione cada linha à tabela
            while (con_cliente.resultset.next()) {
                modelo.addRow(new Object[]{
                    con_cliente.resultset.getString("ID_Empresa"),
                    con_cliente.resultset.getString("Nome_Empresa"),
                    con_cliente.resultset.getString("CNPJ"),
                    con_cliente.resultset.getString("Estado"),
                    con_cliente.resultset.getString("Cidade")
                });
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar os dados da tabela: " + erro.getMessage(), "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void posicionarRegistro() {
        try {
            // Posicione o cursor no primeiro registro
            con_cliente.resultset.first();

            // Mostre os dados do registro atual
            mostrar_Dados();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no primeiro registro: " + erro.getMessage(), "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void mostrar_Dados() {
        try {
            String estadoNoBanco = con_cliente.resultset.getString("Estado");
            txt_ID_Empresa.setText(con_cliente.resultset.getString("ID_Empresa"));
            txt_Nome_Empresa.setText(con_cliente.resultset.getString("Nome_Empresa"));
            txt_CNPJ.setText(con_cliente.resultset.getString("CNPJ"));
            txt_Estado.setSelectedItem(estadoNoBanco);
            txt_Cidade.setText(con_cliente.resultset.getString("Cidade"));
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Não foi possível localizar dados: " + erro.getMessage(), "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCadastroEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JTable empresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JFormattedTextField txt_CNPJ;
    private javax.swing.JTextField txt_Cidade;
    private javax.swing.JComboBox<String> txt_Estado;
    private javax.swing.JTextField txt_ID_Empresa;
    private javax.swing.JTextField txt_Nome_Empresa;
    // End of variables declaration//GEN-END:variables
}
