
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author letic
 */

/** resolver problemas:
 * quando a janela tlBuscarVagas é puxada ele tambem puxa a msg do conexão "conexão estabelecida"
 * os dados da tabela nao estao sendo puxados (concertado)
 * id da vaga deveria ser AI - problemas com preenchimento de tabela (deixar campo invisivel para preenchimento como o de candidato 
 * - aparecer so no banco ou deixar so visualização <- procurar em propriedades op enable ou editable (acho q pra funcionar precisa do AI ligado)
 */ 



import conexao.conexao; //importar do package a classe
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;//para reconhecimento da JTable
import java.sql.*; //para reconhecimento dos comados sql

public class tlBuscarVagas extends javax.swing.JFrame {
    conexao projeto_ds;
    /**
     * Creates new form tlBuscarVagas
     */
    public tlBuscarVagas() {
        initComponents();
        projeto_ds = new conexao(); //iniciação do objeto como instância
        projeto_ds.conecta(); //chama o método que conecta
        projeto_ds.executaSQL("select * from vagas order by ID_vaga");
	preencherTabela();
        posicionarRegistro();
        vagas.setAutoCreateRowSorter(true); //ativa a classificação ordenada da tabela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bntVoltarJanela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vagas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_pesquisa = new javax.swing.JTextField();
        btnVoltarInicio = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Candidato");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntVoltarJanela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volte.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("Busca por Vagas");

        vagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Vaga", "Número de Vagas", "Cargo", "Descrição", "Salário"
            }
        ));
        jScrollPane1.setViewportView(vagas);

        jLabel3.setText("Pesquisa por Cargo:");

        txt_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisaKeyReleased(evt);
            }
        });

        btnVoltarInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botao-home.png"))); // NOI18N
        btnVoltarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntVoltarJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(253, 253, 253))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bntVoltarJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(btnVoltarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE))
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisaKeyReleased
        // TODO add your handling code here:
        try{
            String pesquisa = "select * from vagas where cargo like '" +txt_pesquisa.getText() + "%'";
            projeto_ds.executaSQL(pesquisa);
            
            if(projeto_ds.resultset.first()){
                preencherTabela();
            }
            else{
                 JOptionPane.showMessageDialog(null,"\n Não existe dados com este paramêtro!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);                
            }      
        }catch (SQLException errosql){
           JOptionPane.showMessageDialog(
                    null,
                    "\n Os dados digitados não foram localizados!! : \n" + errosql,
                    "Mensagem do Programa",
                    JOptionPane.INFORMATION_MESSAGE
            ); 
        }
    }//GEN-LAST:event_txt_pesquisaKeyReleased

    private void btnVoltarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarInicioActionPerformed

     public void preencherTabela(){
         //tblClientes é o nome da variavel da tabela
        vagas.getColumnModel().getColumn(0).setPreferredWidth(4);
        vagas.getColumnModel().getColumn(1).setPreferredWidth(150);
        vagas.getColumnModel().getColumn(2).setPreferredWidth(11);
        vagas.getColumnModel().getColumn(3).setPreferredWidth(14);
        vagas.getColumnModel().getColumn(4).setPreferredWidth(100);

        DefaultTableModel modelo = (DefaultTableModel) vagas.getModel();
        modelo.setNumRows(0);

        try {
            projeto_ds.resultset.beforeFirst();
            while (projeto_ds.resultset.next()) {
                modelo.addRow(new Object[]{
                    projeto_ds.resultset.getString("ID_vaga"),
                    projeto_ds.resultset.getString("N_vagas"),
                    projeto_ds.resultset.getString("cargo"),
                    projeto_ds.resultset.getString("descricao"),
                    projeto_ds.resultset.getString("salario")
                });
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(
                    null,
                    "\n Erro ao listar dados da tabela!! :\n" + erro,
                    "Mensagem do Programa",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
     
    public void posicionarRegistro(){
        try{
             projeto_ds.resultset.first(); // posiciona no 1º registro da tabela
             //mostrar_Dados(); //chama o metodo que ira busca o dado da tabela
        }catch(SQLException erro){
         JOptionPane.showMessageDialog(null, "Não localizou dados: " +erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }    
   /* public void mostrar_Dados(){
        try{
            txtCod.setText(projeto_ds.resultset.getString("cod")); //Associar a caixa de texto do campo cod
            txtNome.setText(projeto_ds.resultset.getString("nome")); 
            txtNasc.setText(projeto_ds.resultset.getString("dt_nasc")); 
            txtFone.setText(projeto_ds.resultset.getString("telefone")); 
            txtEmail.setText(projeto_ds.resultset.getString("email")); 
        }catch(SQLException erro){
         JOptionPane.showMessageDialog(null, "Não localizou dados: " +erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tlBuscarVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tlBuscarVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tlBuscarVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tlBuscarVagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tlBuscarVagas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVoltarJanela;
    private javax.swing.JButton btnVoltarInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_pesquisa;
    private javax.swing.JTable vagas;
    // End of variables declaration//GEN-END:variables
}
