/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author letic
 */
import conexao.conexao; //importar do package a classe
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;//para reconhecimento da JTable
import java.sql.*; //para reconhecimento dos comados sql
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;

public class tlCandidatoForm extends javax.swing.JFrame {
    conexao projeto_ds;
    MaskFormatter mfdata, mfFone, mfCPF;
    
   
    public tlCandidatoForm() {
        try {
            mfdata = new MaskFormatter("##/##/####");
             mfFone = new MaskFormatter("+## ## ####-#####");
              mfCPF = new MaskFormatter("#########-##");
        } catch (ParseException ex) {
            System.out.print("ocorreu um erro ao criar a máscara - MENSAGEM DO SISTEMA");
        }
        
        initComponents();
        projeto_ds = new conexao(); //iniciação do objeto como instância
        projeto_ds.conecta(); //chama o método que conecta
        projeto_ds.executaSQL("select * from candidato order by ID_Cand");
	//preencherTabela();
        //posicionarRegistro();
        //tblCandidato.setAutoCreateRowSorter(true); //ativa a classificação ordenada da tabela   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        btnLimpa = new javax.swing.JButton();
        jFData_nasc = new javax.swing.JFormattedTextField(mfdata);
        jLabel10 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jFFone = new javax.swing.JFormattedTextField(mfFone);
        jFCPF = new javax.swing.JFormattedTextField(mfCPF);
        bntVoltarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Telefone:");

        btnLimpa.setBackground(new java.awt.Color(102, 153, 255));
        btnLimpa.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpa.setText("Limpar");
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        jFData_nasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFData_nascFocusGained(evt);
            }
        });
        jFData_nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFData_nascActionPerformed(evt);
            }
        });

        jLabel10.setText("Data de nascimento:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Candidato");

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Rua:");

        jLabel5.setText("Estado:");

        jLabel6.setText("Bairro:");

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DF - Distrito Federal", "GO - Goiás", "MT - Mato Grosso", "MS - Mato Grosso do Sul", "AL - Alagoas", "BA - Bahia", "CE - Ceará", "MA - Maranhão", "PB - Paraíba", "PE - Pernambuco", "PI - Piauí", "RN - Rio Grande do Norte", "SE - Sergipe", "AC - Acre", "AP - Amapá", "AM - Amazonas", "PA - Pará", "RO - Rondônia", "RR - Roraima", "TO - Tocantis", "ES - Espírito Santo", "MG - Minas Gerais", "RJ - Rio de Janeiro", "SP - São Paulo", "PR - Paraná", "RS - Rio Grande do Sul", "SC - Santa Catarina" }));

        jLabel7.setText("Email:");

        jLabel8.setText("Cidade:");

        btnCadastrar.setBackground(new java.awt.Color(102, 153, 255));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jFFone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFFoneFocusGained(evt);
            }
        });
        jFFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFFoneActionPerformed(evt);
            }
        });

        jFCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFCPFFocusGained(evt);
            }
        });
        jFCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFCPFActionPerformed(evt);
            }
        });

        bntVoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volte.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(21, 21, 21)
                                        .addComponent(jComboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                            .addComponent(txtEmail)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jFData_nasc))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jFFone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(bntVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jFFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jFData_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFData_nascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFData_nascActionPerformed
        // TODO add your handling code here:  
        // Define a posição do cursor para o início do campo
    
    }//GEN-LAST:event_jFData_nascActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String telefone = jFFone.getText();
        String data_nasc = jFData_nasc.getText();
        String cpf = jFCPF.getText();
        String rua = txtRua.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = jComboEstado.getSelectedItem().toString();
        
        
        try{
            String insert_sql = "insert into candidato (Nome_cand, telefone, email, dt_nasc, CPF, Cidade, bairro, rua, Estado) values ('" + nome + "','" + telefone + "','" + email + "','" + data_nasc + "','" + cpf + "','" + cidade + "','" + bairro + "','" + rua + "','" + estado + "')";
            projeto_ds.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação finalizada com sucesso!!", "Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            projeto_ds.executaSQL("select * from candidato order by ID_Cand");
            projeto_ds.resultset.first();  
            
            //chamar nova tela assim que o cadastro for concluido
             tlBuscarVagas vagas = new tlBuscarVagas();
                vagas.setVisible(true);
            
            
        } catch (SQLException errosql) {
            JOptionPane.showMessageDialog(
                    null,
                    "\n Erro na gravação: \n" + errosql,
                    "Mensagem do Programa",
                    JOptionPane.INFORMATION_MESSAGE
            );
    }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        // TODO add your handling code here:
        txtNome.setText("");
        txtEmail.setText("");
        jFData_nasc.setText("");
        jFFone.setText(""); //Formatação dos campos telefone, dtNasc e cpf
        jFCPF.setText("");
        txtCidade.setText("");
        txtBairro.setText("");
        txtRua.setText("");
        jComboEstado.setSelectedIndex(0);
        txtNome.requestFocus();
        
    }//GEN-LAST:event_btnLimpaActionPerformed

    private void jFFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFFoneActionPerformed
        // TODO add your handling code here:
        // Define a posição do cursor para o início do campo
    
    }//GEN-LAST:event_jFFoneActionPerformed

    private void jFCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFCPFActionPerformed

    private void jFFoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFFoneFocusGained
        // TODO add your handling code here:
        // Define a posição do cursor para o início do campo
    jFFone.setCaretPosition(0);
    }//GEN-LAST:event_jFFoneFocusGained

    private void jFData_nascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFData_nascFocusGained
        // TODO add your handling code here:
        // Define a posição do cursor para o início do campo
    jFData_nasc.setCaretPosition(0);
    }//GEN-LAST:event_jFData_nascFocusGained

    private void jFCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFCPFFocusGained
        // TODO add your handling code here:
        // Define a posição do cursor para o início do campo
    jFCPF.setCaretPosition(0);
    }//GEN-LAST:event_jFCPFFocusGained
      
    /*private void preencherTabela(){
         //tblClientes é o nome da variavel da tabela
        tblCandidato.getColumnModel().getColumn(0).setPreferredWidth(4);
        tblCandidato.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblCandidato.getColumnModel().getColumn(2).setPreferredWidth(11);
        tblCandidato.getColumnModel().getColumn(3).setPreferredWidth(14);
        tblCandidato.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblCandidato.getColumnModel().getColumn(5).setPreferredWidth(100);
        tblCandidato.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblCandidato.getColumnModel().getColumn(7).setPreferredWidth(100);
        tblCandidato.getColumnModel().getColumn(8).setPreferredWidth(100);

        DefaultTableModel modelo = (DefaultTableModel) tblCandidato.getModel();
        modelo.setNumRows(0);

        try {
            projeto_ds.resultset.beforeFirst();
            while (projeto_ds.resultset.next()) {
                modelo.addRow(new Object[]{
                   // projeto_ds.resultset.getString("cod"),
                    projeto_ds.resultset.getString("nome"),
                    projeto_ds.resultset.getString("dt_nasc"),
                    projeto_ds.resultset.getString("telefone"),
                    projeto_ds.resultset.getString("email"),
                    projeto_ds.resultset.getString("cpf"),
                    projeto_ds.resultset.getString("rua"),
                    projeto_ds.resultset.getString("bairro"),
                    projeto_ds.resultset.getString("cidade"),
                    projeto_ds.resultset.getString("estado")
                });
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(
                    null,
                    "\n Erro ao listar dados da tabela! :\n" + erro,
                    "Mensagem do Programa",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
     
    private void posicionarRegistro(){
        try{
             projeto_ds.resultset.first(); // posiciona no 1º registro da tabela
             mostrar_Dados(); //chama o metodo que ira busca o dado da tabela
        }catch(SQLException erro){
         JOptionPane.showMessageDialog(null, "Não localizou dados: " +erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }    
    public void mostrar_Dados(){
        try{
            //txtCod.setText(projeto_ds.resultset.getString("cod")); //Associar a caixa de texto do campo cod
            txtNome.setText(projeto_ds.resultset.getString("nome")); 
            txtEmail.setText(projeto_ds.resultset.getString("email"));
            jFFone.setText(projeto_ds.resultset.getString("telefone")); 
            jFData_nasc.setText(projeto_ds.resultset.getString("dt_nasc"));
            jFCPF.setText(projeto_ds.resultset.getString("cpf"));
            txtCidade.setText(projeto_ds.resultset.getString("cidade"));
            txtBairro.setText(projeto_ds.resultset.getString("bairro"));
            txtRua.setText(projeto_ds.resultset.getString("rua"));
            jComboEstado.setSelectedItem(projeto_ds.resultset.getString("estado"));
        
            
        }catch(SQLException erro){
         JOptionPane.showMessageDialog(null, "Não localizou dados: " +erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }*/
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tlCandidatoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tlCandidatoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tlCandidatoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tlCandidatoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tlCandidatoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVoltarMenu;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JComboBox<String> jComboEstado;
    private javax.swing.JFormattedTextField jFCPF;
    private javax.swing.JFormattedTextField jFData_nasc;
    private javax.swing.JFormattedTextField jFFone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
